import React from 'react'
import Head from "next/head";
import {
	FaFacebookF,
	FaLinkedinIn,
	FaGoogle,
	FaRegEnvelope,
  } from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";

function signup() {
  return (
<div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
          <div className="w-3/5 p-5">
            <div className="text-left font-bold">
              <span className="text-orange-400">Trail</span>
              Shoppy
            </div>
            <div className="py-10">
              <h2 className="text-2xl font-bold mb-2">Sign in to Account</h2>
              <div className="flex justify-center my-2">
                <a
                  href="#"
                  className="border-2 border-gray-200 rounded-full p-3 mx-1"
                >
                  <FaFacebookF className="text-sm" />
                </a>
                <a
                  href="#"
                  className="border-2 border-gray-200 rounded-full p-3 mx-1"
                >
                  <FaLinkedinIn className="text-sm" />
                </a>
                <a
                  href="#"
                  className="border-2 border-gray-200 rounded-full p-3 mx-1"
                >
                  <FaGoogle className="text-sm" />
                </a>
              </div>
              <p className="text-gray-400 my-3">or use email account?</p>

              <div className="flex flex-col items-center mb-3">
                <div className="bg-gray-100 w-64 p-2 flex items-center ">
                  <FaRegEnvelope className="text=gray-300 mr-2" />
                  <input
                    className="bg-gray-100 outline-none text-sm flex-1 "
                    type="email"
                    name="email"
                    placeholder="User ID/Email"
                  />
                </div>
              </div>
              <div className="flex flex-col items-center">
                <div className="bg-gray-100 w-64 p-2 flex items-center ">
                  <MdLockOutline className="text=gray-300 mr-2" />
                  <input
                    className="bg-gray-100 outline-none text-sm flex-1 "
                    type="password"
                    name="Password"
                    placeholder="PassWord"
                  />
                </div>

                <div className="flex justify-between w-64 mb-5">
                  <label className="flex items-center text-xs">
                    <input type="checkbox" name="remember" className="mr-1" />
                    Remember Me{" "}
                  </label>
                  <a href="#" className="text-sm">
                    Forget PassWord?
                  </a>
                </div>
                <a
                  className="border-2 border-orange rounded-full px-12 py-2 inline-block font-semibold hover:bg-orange-300 hover:text-black-400"
                  href="#"
                >
                  SignUp
                </a>
              </div>
            </div>
          </div>
          <div className="w-2/5 bg-orange-200 rounded-tr-2xl rounded-br-2xl py-36 px-12">
            <h2 className="text-3xl font-bold mb-2">Hello, User!</h2>
            <div className="border-2 w-10 border-white inline-block mb-2"></div>
            <p className="mb-10">
              Fill up personal information and start journey with us.
            </p>
            <a
              className="border-2 border-white rounded-full px-12 py-2 inline-block font-semibold hover:bg-white hover:text-orange-400"
              href="#"
            >
              SignIn
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default signup